# Generated by Django 5.1.6 on 2025-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_films_trailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='укажите описание фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='image',
            field=models.ImageField(null=True, upload_to='films/', verbose_name='загрузите фото'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите название фильма'),
        ),
    ]
