# Generated by Django 5.1.6 on 2025-03-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_films_options_alter_films_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('grade', models.CharField(choices=[('💥', '💥'), ('💥💥', '💥💥'), ('💥💥💥', '💥💥💥'), ('💥💥💥💥', '💥💥💥💥'), ('💥💥💥💥💥', '💥💥💥💥💥')], default='💥', max_length=10)),
                ('choice_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.films')),
            ],
        ),
    ]
