# Generated by Django 5.1.6 on 2025-03-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_alter_rezkafilmsmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezkafilmsmodel',
            name='image',
        ),
    ]
